services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - mynet
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: app.Dockerfile    
      # dockerfile: app_graal.Dockerfile
    # image: darcusgrey/employee-app
    networks: 
      - mynet
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
    depends_on:
      - db
    environment:
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE_LOG: file:db/changelog/db.changelog-master.xml
    env_file:
      - .env
    
volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
  