services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - mynet
    env_file:
      - .env

  liquibase-update:
    build:
      context: .
      dockerfile: liquibase.Dockerfile
    depends_on:
      - db
    #Use this for dev, for prod use COPY in image Dockerfile.
    volumes:
      - ./db/changelog:/liquibase/changelog
    command:
      - update
    environment:
      LIQUIBASE_COMMAND_URL: ${DB_URL}
      LIQUIBASE_COMMAND_USERNAME: ${DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASS}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-master.xml
    env_file:
      - .env
    networks:
      - mynet

  liquibase:
    profiles:
      - tools
    build:
      context: .
      dockerfile: liquibase.Dockerfile
    depends_on:
      - db
    #Use this for dev, for prod use COPY in image Dockerfile.
    environment:
      LIQUIBASE_COMMAND_URL: ${DB_URL}
      LIQUIBASE_COMMAND_USERNAME: ${DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASS}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-master.xml
    volumes:
      - ./db/changelog:/liquibase/changelog
    env_file:
      - .env
    networks:
      - mynet

  server:
    build:
      context: .
      dockerfile: app.Dockerfile    
      # dockerfile: app_graal.Dockerfile
    # image: darcusgrey/employee-app
    networks: 
      - mynet
    ports:
      - "8080:8080"
    depends_on:
      liquibase-update:
        condition: service_completed_successfully
    environment:
      SPRING_LIQUIBASE_ENABLED: false
    env_file:
      - .env
    
volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
  